### ISSUE TITLE
Python2 compatibility broken by MR #23

### ISSUE THREAD

**Issue by samveen** [python-oca/python-oca#30]
The merge request #23  has broken compatibility with python2.
```
samveen@spsmaster:~$ python  vmlist.py 
Traceback (most recent call last):
  File "vmlist.py", line 2, in <module>
    import oca
  File "/home/samveen/.local/lib/python2.7/site-packages/oca/__init__.py", line 7, in <module>
    import http.client
ImportError: No module named http.client
```

**Comment by samveen** [comment]
Closing this ticket as the problem is at my end: I was missing the python `future` module on my end.

**Comment by sysradium** [comment]
@samveen 
This is interesting, because there is a future listed in the dependencies: https://github.com/python-oca/python-oca/blob/master/setup.py

**Comment by samveen** [comment]
It'st still an idiot problem on my part, as I did a manual pull, not a `pip install`. Apologies on wasting more of your time.
