### ISSUE TITLE
Not all lcm_states are decoded

### ISSUE THREAD

**Issue by Demianyk** [python-oca/python-oca#32]
Schemas for Virtual Machine
In vm.py (45) there are only 18 states described in LCM_STATE list, whilst there is much more states which can be returned by Opennebula API (http://docs.opennebula.org/4.14/integration/system_interfaces/api.htm) (see Schemas for Virtual Machine).

**Comment by samveen** [comment]
Details of states in 4.14.2: http://docs.opennebula.org/4.14/integration/system_interfaces/api.html#schemas-for-virtual-machine

**Comment by sysradium** [comment]
OK guys, will fix that soon.
