### ISSUE TITLE
[Feature Request] Add `one.vmpool.accounting` to `VirtualMachinePool`

### ISSUE THREAD

**Issue by samveen** [python-oca/python-oca#33]
It would be great if a method for `one.vmpool.accounting` could be added to `VirtualMachinePool` class.
http://docs.opennebula.org/4.12/integration/system_interfaces/api.html#one-vmpool-accounting

**Comment by sysradium** [comment]
👍 great, thanks, will when I have a few free minutes :)

**Comment by samveen** [comment]
Marking this as closed, given that OpenNebula now provides [it's own python API](https://docs.opennebula.io/6.8/integration_and_development/system_interfaces/python.html#api-documentation)
