### ISSUE TITLE
oca.VirtualMachine.allocate missing flag and oca.VirtualMachine.rename

### ISSUE THREAD

**Issue by Demonsthere** [python-oca/python-oca#51]
Hey guys,
Would it be possible to add the missing bool flag for the allocate method?
`IN	Boolean	False to create the VM on pending (default), True to create it on hold.`
Together with the missing `rename` function it would make possible to spawn machines using allocate, which set a default name for the machine, set it by default to hold, and then rename it to a more friendly name. Sadly, the only method now to create a named machine is by the template method.

**Comment by mguezuraga** [comment]
Hi,

I don't understand the argument of creating a VM with 'a more friendly name'.

You can already do:

> tmpl.instantiate(name='my-custom-name')

Am I'm missing something?

**Comment by Demonsthere** [comment]
Sorry, i honestly forgot what I was trying to do there... Closing
